version: 2
jobs:
  build:
    docker:
      - image: circleci/node:14.16.1
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies

      - run: npm install

      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules

      - run: npm test
      - run: npm run lint
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: LE
experimental:
  notify:
    branches:
      only:
        - master